# Generated by Django 4.2.5 on 2023-09-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_datecompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='dueto',
        ),
    ]
